### ISSUE TITLE
Remove next() from controller action parameters

### ISSUE THREAD

**Issue by pacovell** [donedotcom/dispatch#2]
For most calls, the controller action is the last step in the processing pipeline, so next() can be removed as a normal parameter.  We can add it to res (res.next()) for the case where someone actually wants to call it.

Before hooks still need to receive (their version of) next() so they can pass control to the next before hook or the action itself.

**Comment by joshleitzel** [comment]
Closed by 262f6bb759dc1dbdf12dd4c09a00ebec2ee5c405
